Doors, Better depth management
frankvHoof93/RPGWizardry pull request #22
Opened 2019-12-05 15:38 UTC by Svenpai

2019-12-05 15:47 UTC, frankvHoof93 requested changes

2019-12-05 15:47 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/GameWorld/BackwallManager.cs
> +        void Start()
Set accessibility modifier (private)

2019-12-05 15:47 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/GameWorld/BackwallManager.cs
> +                foreach (Tilemap s in Walls)
Use a for-loop instead of a foreach-loop to prevent allocating memory for the loop

2019-12-05 15:47 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/GameWorld/BackwallManager.cs
> +                foreach (Tilemap s in Walls)
Use a for-loop instead of a foreach-loop to prevent allocating memory for the loop

2019-12-05 15:47 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/GameWorld/EnvironmentOpacityManager.cs
> +    public class EnvironmentOpacityManager : MonoBehaviour
How is this class different from BackWallManager?

2019-12-05 15:47 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/GameWorld/EnvironmentOpacityManager.cs
> +            int output = Collider.OverlapCollider(ContactFilter, results);
return bool (see BackWallManager)

2019-12-06 10:08 UTC, frankvHoof93 approved these changes

2019-12-06 10:37 UTC, Sanko-Kallig approved these changes

2019-12-06 10:43 UTC, merged