Slime knockback, hitstun, game reload bugfix
frankvHoof93/RPGWizardry pull request #74
Opened 2020-01-23 14:15 UTC by Svenpai

2020-01-23 14:23 UTC, frankvHoof93 requested changes

2020-01-23 14:23 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/Player/Movement/MovementManager.cs
> +        public bool Stunned;
Plz do this more cleanly

2020-01-23 14:23 UTC, frankvHoof93 commented on RPG Wizardry/Assets/Scripts/Player/PlayerManager.cs
> +        private IEnumerator Stun(float duration)
Summary

2020-01-23 21:34 UTC, frankvHoof93 approved these changes

2020-01-24 09:08 UTC, Thorvers approved these changes

2020-01-24 09:09 UTC, merged